// Mocks generated by Mockito 5.2.0 from annotations
// in tabata/test/presentation/launch_screen/launch_screen_bloc_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:tabata/domain/usecases/auth/is_user_authenticated_use_case_impl.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [IsUserAuthenticatedUseCaseImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsUserAuthenticatedUseCaseImpl extends _i1.Mock
    implements _i2.IsUserAuthenticatedUseCaseImpl {
  MockIsUserAuthenticatedUseCaseImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []), returnValue: false)
          as bool);
}
