// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_UZIxFZSqTk0NRu1cbhVIxe9MjXEpIUA',
    appId: '1:672904104578:web:6de7e5e3fe6a64e022829b',
    messagingSenderId: '672904104578',
    projectId: 'tabata-dgw16',
    authDomain: 'tabata-dgw16.firebaseapp.com',
    storageBucket: 'tabata-dgw16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIi17aOujZTKM5CMGR_L1C0l9xNnbMUsU',
    appId: '1:672904104578:android:9e58021f8d1cbc9722829b',
    messagingSenderId: '672904104578',
    projectId: 'tabata-dgw16',
    storageBucket: 'tabata-dgw16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu14RgE8wLGjFOMjFRPDCrLR60cdp3oQE',
    appId: '1:672904104578:ios:6499882cec41681d22829b',
    messagingSenderId: '672904104578',
    projectId: 'tabata-dgw16',
    storageBucket: 'tabata-dgw16.appspot.com',
    iosClientId: '672904104578-uphghjn2rivad5hv1cp71juilkuravbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu14RgE8wLGjFOMjFRPDCrLR60cdp3oQE',
    appId: '1:672904104578:ios:6499882cec41681d22829b',
    messagingSenderId: '672904104578',
    projectId: 'tabata-dgw16',
    storageBucket: 'tabata-dgw16.appspot.com',
    iosClientId: '672904104578-uphghjn2rivad5hv1cp71juilkuravbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabata',
  );
}
